export const categories = [
  {
    id: "1",
    name: "Pizza",
    icon: "🍕",
    restaurants: [
      {
        id: "p1",
        name: "Pizza Paradise",
        image: "🍕",
        rating: 4.8,
        cuisine: "Italian",
        deliveryTime: "25-35 min",
        menu: [
          {
            id: "m1",
            name: "Margherita",
            price: 12.99,
            description: "Fresh tomatoes, mozzarella, basil",
            image:
              "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500",
            ingredients: [
              "Fresh Mozzarella",
              "Roma Tomatoes",
              "Fresh Basil",
              "Extra Virgin Olive Oil",
              "Salt and Pepper",
            ],
            nutrition: {
              calories: 850,
              protein: 34,
              carbs: 98,
              fat: 26,
              fiber: 4,
            },
            allergens: ["Dairy", "Gluten"],
          },
          {
            id: "m2",
            name: "Pepperoni",
            price: 14.99,
            description: "Pepperoni, cheese, tomato sauce",
            image:
              "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500",
            ingredients: [
              "Italian Pepperoni",
              "Mozzarella Cheese",
              "Tomato Sauce",
              "Italian Herbs",
              "Olive Oil",
            ],
            nutrition: {
              calories: 1000,
              protein: 40,
              carbs: 120,
              fat: 30,
              fiber: 5,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
      {
        id: "p2",
        name: "Pizza Hub",
        image: "🍕",
        rating: 4.5,
        cuisine: "Italian",
        deliveryTime: "30-40 min",
        menu: [
          {
            id: "m3",
            name: "Hawaiian",
            price: 13.99,
            description: "Ham, pineapple, mozzarella",
            image:
              "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500",
            ingredients: [
              "Ham",
              "Fresh Pineapple",
              "Mozzarella Cheese",
              "Tomato Sauce",
              "Italian Herbs",
              "Extra Virgin Olive Oil",
            ],
            nutrition: {
              calories: 1200,
              protein: 45,
              carbs: 150,
              fat: 35,
              fiber: 7,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Burger",
    icon: "🍔",
    restaurants: [
      {
        id: "b1",
        name: "Burger House",
        image: "🍔",
        rating: 4.6,
        cuisine: "American",
        deliveryTime: "20-30 min",
        menu: [
          {
            id: "m4",
            name: "Classic Burger",
            price: 9.99,
            description: "Beef patty, lettuce, tomato, cheese",
            image:
              "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
            ingredients: [
              "100% Beef Patty",
              "Fresh Lettuce",
              "Tomato Slices",
              "Cheddar Cheese",
              "Red Onions",
              "Special Sauce",
              "Sesame Bun",
            ],
            nutrition: {
              calories: 1500,
              protein: 60,
              carbs: 180,
              fat: 70,
              fiber: 10,
            },
            allergens: ["Dairy", "Gluten"],
          },
          {
            id: "m5",
            name: "Chicken Burger",
            price: 8.99,
            description: "Grilled chicken, mayo, lettuce",
            image:
              "https://images.unsplash.com/photo-1615297928064-24977384d0da?w=500",
            ingredients: [
              "Grilled Chicken Breast",
              "Fresh Lettuce",
              "Tomato Slices",
              "Mayonnaise",
              "Pickles",
              "Brioche Bun",
            ],
            nutrition: {
              calories: 1200,
              protein: 50,
              carbs: 150,
              fat: 50,
              fiber: 5,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
      {
        id: "b2",
        name: "Gourmet Burgers",
        image: "🍔",
        rating: 4.7,
        cuisine: "American",
        deliveryTime: "25-35 min",
        menu: [
          {
            id: "m6",
            name: "Deluxe Burger",
            price: 15.99,
            description: "Wagyu beef, truffle mayo, aged cheddar",
            image:
              "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=500",
            ingredients: [
              "Wagyu Beef Patty",
              "Aged Cheddar",
              "Truffle Mayonnaise",
              "Caramelized Onions",
              "Arugula",
              "Brioche Bun",
            ],
            nutrition: {
              calories: 2000,
              protein: 80,
              carbs: 200,
              fat: 100,
              fiber: 15,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Sushi",
    icon: "🍱",
    restaurants: [
      {
        id: "s1",
        name: "Sushi Master",
        image: "🍱",
        rating: 4.9,
        cuisine: "Japanese",
        deliveryTime: "30-40 min",
        menu: [
          {
            id: "m7",
            name: "California Roll",
            price: 10.99,
            description: "Crab, avocado, cucumber",
            image:
              "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=500",
            ingredients: [
              "Imitation Crab Meat",
              "Ripe Avocado",
              "Fresh Cucumber",
              "Sushi Rice",
              "Nori Seaweed",
              "Sesame Seeds",
            ],
            nutrition: {
              calories: 1000,
              protein: 30,
              carbs: 150,
              fat: 30,
              fiber: 5,
            },
            allergens: ["Dairy", "Gluten"],
          },
          {
            id: "m8",
            name: "Salmon Nigiri",
            price: 12.99,
            description: "Fresh salmon over rice",
            image:
              "https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=500",
            ingredients: [
              "Fresh Salmon",
              "Sushi Rice",
              "Wasabi",
              "Pickled Ginger",
              "Soy Sauce",
            ],
            nutrition: {
              calories: 1200,
              protein: 40,
              carbs: 180,
              fat: 50,
              fiber: 7,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
      {
        id: "s2",
        name: "Tokyo Sushi",
        image: "🍱",
        rating: 4.7,
        cuisine: "Japanese",
        deliveryTime: "35-45 min",
        menu: [
          {
            id: "m9",
            name: "Dragon Roll",
            price: 16.99,
            description: "Eel, avocado, cucumber, special sauce",
            image:
              "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=500",
            ingredients: [
              "Grilled Eel",
              "Ripe Avocado",
              "Fresh Cucumber",
              "Sushi Rice",
              "Nori Seaweed",
              "Unagi Sauce",
              "Sesame Seeds",
            ],
            nutrition: {
              calories: 1500,
              protein: 40,
              carbs: 180,
              fat: 60,
              fiber: 10,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
    ],
  },
  {
    id: "4",
    name: "Pasta",
    icon: "🍝",
    restaurants: [
      {
        id: "pa1",
        name: "Pasta Palace",
        image: "🍝",
        rating: 4.6,
        cuisine: "Italian",
        deliveryTime: "25-35 min",
        menu: [
          {
            id: "m10",
            name: "Spaghetti Carbonara",
            price: 14.99,
            description: "Eggs, pecorino cheese, pancetta, black pepper",
            image:
              "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500",
            ingredients: [
              "Spaghetti Pasta",
              "Pancetta",
              "Fresh Eggs",
              "Pecorino Romano",
              "Parmigiano Reggiano",
              "Black Pepper",
              "Extra Virgin Olive Oil",
            ],
            nutrition: {
              calories: 1800,
              protein: 70,
              carbs: 200,
              fat: 70,
              fiber: 15,
            },
            allergens: ["Dairy", "Gluten"],
          },
          {
            id: "m11",
            name: "Fettuccine Alfredo",
            price: 13.99,
            description: "Creamy parmesan sauce",
            image:
              "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=500",
            ingredients: [
              "Fettuccine Pasta",
              "Heavy Cream",
              "Parmesan Cheese",
              "Butter",
              "Garlic",
              "Black Pepper",
              "Fresh Parsley",
            ],
            nutrition: {
              calories: 1500,
              protein: 50,
              carbs: 180,
              fat: 80,
              fiber: 10,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
    ],
  },
  {
    id: "5",
    name: "Salad",
    icon: "🥗",
    restaurants: [
      {
        id: "sa1",
        name: "Green Bowl",
        image: "🥗",
        rating: 4.5,
        cuisine: "Healthy",
        deliveryTime: "15-25 min",
        menu: [
          {
            id: "m12",
            name: "Caesar Salad",
            price: 8.99,
            description: "Romaine lettuce, croutons, parmesan",
            image:
              "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=500",
            ingredients: [
              "Romaine Lettuce",
              "Homemade Croutons",
              "Parmesan Cheese",
              "Caesar Dressing",
              "Black Pepper",
              "Anchovies (Optional)",
            ],
            nutrition: {
              calories: 1000,
              protein: 20,
              carbs: 100,
              fat: 50,
              fiber: 10,
            },
            allergens: ["Dairy", "Gluten"],
          },
          {
            id: "m13",
            name: "Greek Salad",
            price: 9.99,
            description: "Feta cheese, olives, cucumber, tomatoes",
            image:
              "https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=500",
            ingredients: [
              "Cucumber",
              "Tomatoes",
              "Red Onion",
              "Feta Cheese",
              "Kalamata Olives",
              "Extra Virgin Olive Oil",
              "Oregano",
            ],
            nutrition: {
              calories: 800,
              protein: 20,
              carbs: 100,
              fat: 30,
              fiber: 10,
            },
            allergens: ["Dairy", "Gluten"],
          },
        ],
      },
    ],
  },
];

// For the home screen's popular restaurants section
export const popularRestaurants = [
  {
    id: "p1",
    name: "Pizza Paradise",
    image: "🍕",
    rating: 4.8,
    cuisine: "Italian",
    deliveryTime: "25-35 min",
  },
  {
    id: "b1",
    name: "Burger House",
    image: "🍔",
    rating: 4.6,
    cuisine: "American",
    deliveryTime: "20-30 min",
  },
  {
    id: "s1",
    name: "Sushi Master",
    image: "🍱",
    rating: 4.9,
    cuisine: "Japanese",
    deliveryTime: "30-40 min",
  },
];
